[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
rand = "0.8"

[[bin]]
name = "histogram"
path = "src/bin/histogram.rs"

[[bin]]
name = "merge_sort"
path = "src/bin/merge_sort.rs"
